BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Artist" (
	"artist_id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL,
	"genre"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "Tab" (
	"tab_id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"content"	TEXT NOT NULL,
	"title"	TEXT NOT NULL,
	"description"	TEXT NOT NULL,
	"created_on"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "User" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"username"	TEXT NOT NULL UNIQUE,
	"password"	TEXT NOT NULL
);
COMMIT;
